### ISSUE TITLE
[GooseMod/Topaz] Cannot stop autoscrolling

### ISSUE THREAD

**Issue by couleurm** [programmer-pony/BD-AutoScroll#3]
Hey, once I click the middle mouse button I can't manage to get it to get out of auto-scrolling mode, a tip/fix would be greatly appreciated!

**Comment by hackermare** [comment]
![Uncaught ReferenceError: cancelAnimationFrame is not defined)](https://user-images.githubusercontent.com/15032780/187023906-a6d3d775-f858-48f1-8ed4-40e31a751612.png)
window.cancelAnimationFrame() can't be used. This seems like a mistake, since window.requestAnimationFrame() can be used in fact. I made a pull request on the topaz repo (https://github.com/GooseMod/topaz/pull/1) to fix that. If they merge it, this issue will be fixed too. If they don't, there's not much I can do.

**Comment by couleurm** [comment]
User `george.` on the goosenest discord just told me about the `--enable-blink-features=MiddleClickAutoscroll` which does what you expect, but still pastes when you scroll

**Comment by hackermare** [comment]
Yeah, I know about that Chromium argument. I just don't like it because it doesn't prevent middle click paste. That's why I made this plugin.

**Comment by hackermare** [comment]
Good news: The PR got merged. The plugin will work when the next version of topaz comes out.

**Comment by CanadaHonk** [comment]
Will release next time I'm on PC :+1:
